### ISSUE TITLE
Code optimization

### ISSUE THREAD

**Issue by roddar92** [Alioth6/contact_game_bot#12]
https://github.com/Alioth6/contact_game_bot/blob/9dbbb4d060009310f1333aac202da75fbbec5847/src/bot/settings.py#L70

Судя по всему, а данном коде мы просто отрезаем лишний перевод строки и добавляем слова в список. Можно то дело переписать в одну строку. А ещё воспользоваться методом `strip()` :)

**Comment by Alioth6** [comment]
https://github.com/Alioth6/contact_game_bot/blob/3010c9b0a6c8f31a7ab0ce40e6073f61cfac991f/src/bot/settings.py#L69
Спасибо, поправила.
